---
all:
  vars:
    ansible_connection: network_cli
  hosts:
    master:
      ansible_network_os: linux
      ansible_host: 10.215.119.106
      ansible_connection: ssh
      ansible_ssh_user: master

    slave:
      ansible_network_os: linux
      ansible_host: 10.215.119.180
      ansible_connection: ssh
      ansible_ssh_user: slave 
